import { Denial } from './types';

const sampleDenials: Denial[] = [
  {
    id: 'DEN-001',
    claimNumber: 'CLM-2024-00451',
    patientName: 'Margaret Thompson',
    patientDOB: '1958-03-15',
    payerName: 'UnitedHealthcare',
    payerId: 'UHC-87726',
    providerNPI: '1234567890',
    dateOfService: '2024-11-15',
    denialDate: '2024-12-01',
    cptCode: '99213',
    modifier: '25',
    diagnosisCode: 'M54.5',
    billedAmount: 250.00,
    deniedAmount: 250.00,
    carcCode: 'CO-16',
    rarcCode: 'N286',
    adjustmentGroupCode: 'CO',
    denialCategory: 'missing_information',
    status: 'New',
    priority: 'high',
    createdAt: '2024-12-01T10:30:00Z',
    updatedAt: '2024-12-01T10:30:00Z',
  },
  {
    id: 'DEN-002',
    claimNumber: 'CLM-2024-00452',
    patientName: 'Robert Chen',
    patientDOB: '1972-07-22',
    payerName: 'Aetna',
    payerId: 'AET-54321',
    providerNPI: '1234567890',
    dateOfService: '2024-11-18',
    denialDate: '2024-12-02',
    cptCode: '27447',
    modifier: '',
    diagnosisCode: 'M17.11',
    billedAmount: 28500.00,
    deniedAmount: 28500.00,
    carcCode: 'CO-18',
    rarcCode: 'N335',
    adjustmentGroupCode: 'CO',
    denialCategory: 'duplicate',
    status: 'Analyzed',
    priority: 'critical',
    analysis: {
      denialSummary: 'Claim denied as duplicate submission. The same claim was previously submitted on 11/10/2024 and adjudicated.',
      rootCauseCategory: 'Billing Process Error',
      rootCauseDetail: 'Duplicate claim submitted due to billing system error - resubmission triggered without voiding original.',
      denialCategory: 'duplicate',
      preventable: true,
      correctable: true,
      appealRecommended: false,
      confidenceScore: 0.95,
      recommendedNextAction: 'Void the duplicate claim and verify original claim status. No correction needed if original was paid.',
      requiredInformation: [
        { item: 'Original claim submission date', reasonNeeded: 'To confirm duplicate status' },
        { item: 'Original claim payment status', reasonNeeded: 'To determine if correction is needed' },
      ],
      complianceNotes: ['Verify EFT/ERA for original claim before taking action on duplicate.'],
      analyzedAt: '2024-12-03T09:15:00Z',
    },
    createdAt: '2024-12-02T14:20:00Z',
    updatedAt: '2024-12-03T09:15:00Z',
  },
  {
    id: 'DEN-003',
    claimNumber: 'CLM-2024-00453',
    patientName: 'Sarah Mitchell',
    patientDOB: '1985-11-08',
    payerName: 'Cigna',
    payerId: 'CIG-98765',
    providerNPI: '2345678901',
    dateOfService: '2024-10-25',
    denialDate: '2024-11-15',
    cptCode: '99214',
    modifier: '',
    diagnosisCode: 'F32.1',
    billedAmount: 375.00,
    deniedAmount: 375.00,
    carcCode: 'CO-22',
    rarcCode: 'N425',
    adjustmentGroupCode: 'CO',
    denialCategory: 'bundling',
    status: 'Corrected',
    priority: 'normal',
    analysis: {
      denialSummary: 'Payment adjusted because this procedure/service is bundled with another procedure/service already billed.',
      rootCauseCategory: 'Coding Error',
      rootCauseDetail: 'E/M service bundled with procedure performed same day - modifier 25 not applied.',
      denialCategory: 'bundling',
      preventable: true,
      correctable: true,
      appealRecommended: true,
      confidenceScore: 0.88,
      recommendedNextAction: 'Add modifier 25 to E/M service and resubmit with documentation supporting separate E/M.',
      requiredInformation: [
        { item: 'Separate E/M documentation', reasonNeeded: 'To support modifier 25' },
        { item: 'Procedure note for same-day service', reasonNeeded: 'To establish medical necessity for separate E/M' },
      ],
      complianceNotes: ['Ensure documentation clearly supports a separately identifiable E/M service.'],
      analyzedAt: '2024-11-16T11:00:00Z',
    },
    correction: {
      correctionType: 'Modifier Addition',
      correctionSummary: 'Add modifier 25 to the E/M service (CPT 99214) to indicate a separately identifiable evaluation and management service.',
      correctionRationale: 'The E/M service was provided on the same day as a procedure and the documentation supports a separate, identifiable service. Modifier 25 is required per CCI edits.',
      proposedChanges: [
        {
          fieldPath: 'CPTCode[0].Modifier',
          originalValue: '',
          proposedValue: '25',
          reason: 'To indicate separately identifiable E/M service on same day as procedure',
          riskLevel: 'low',
        },
      ],
      requiredDocuments: [
        { documentType: 'Separate E/M note', reason: 'Must document separately identifiable E/M service' },
        { documentType: 'Procedure note', reason: 'To show the procedure was distinct from E/M' },
      ],
      resubmissionInstructions: {
        claimFrequencyCode: '7',
        submissionType: 'Electronic',
        notes: 'Resubmit as corrected claim with modifier 25. Include supporting documentation.',
      },
      confidenceScore: 0.90,
      riskLevel: 'low',
      complianceNotes: ['Documentation must clearly support separate E/M service per CMS guidelines.'],
      createdAt: '2024-11-17T10:30:00Z',
    },
    createdAt: '2024-11-15T09:45:00Z',
    updatedAt: '2024-11-17T10:30:00Z',
  },
  {
    id: 'DEN-004',
    claimNumber: 'CLM-2024-00454',
    patientName: 'James Wilson',
    patientDOB: '1963-05-30',
    payerName: 'Medicare',
    payerId: 'MCR-00126',
    providerNPI: '3456789012',
    dateOfService: '2024-09-10',
    denialDate: '2024-10-15',
    cptCode: '71046',
    modifier: '',
    diagnosisCode: 'R91.8',
    billedAmount: 325.00,
    deniedAmount: 325.00,
    carcCode: 'CO-27',
    rarcCode: 'N523',
    adjustmentGroupCode: 'CO',
    denialCategory: 'medical_necessity',
    status: 'Reviewed',
    priority: 'high',
    analysis: {
      denialSummary: 'Service denied as not medically necessary based on the diagnosis submitted.',
      rootCauseCategory: 'Medical Necessity',
      rootCauseDetail: 'Chest X-ray (71046) denied - diagnosis R91.8 does not meet medical necessity criteria per LCD.',
      denialCategory: 'medical_necessity',
      preventable: true,
      correctable: true,
      appealRecommended: true,
      confidenceScore: 0.82,
      recommendedNextAction: 'Review clinical documentation for supporting diagnosis. Appeal with additional clinical evidence.',
      requiredInformation: [
        { item: 'Clinical notes supporting medical necessity', reasonNeeded: 'To support appeal' },
        { item: 'Relevant LCD/NCD reference', reasonNeeded: 'To verify coverage requirements' },
      ],
      complianceNotes: ['Appeal must include clinical rationale and supporting documentation per Medicare guidelines.'],
      analyzedAt: '2024-10-16T08:30:00Z',
    },
    correction: {
      correctionType: 'Diagnosis Update',
      correctionSummary: 'Update diagnosis to a covered diagnosis per the applicable LCD, or prepare appeal with clinical documentation.',
      correctionRationale: 'The current diagnosis R91.8 does not meet LCD requirements for chest X-ray coverage. Clinical documentation may support an alternative covered diagnosis.',
      proposedChanges: [
        {
          fieldPath: 'DiagnosisCode',
          originalValue: 'R91.8',
          proposedValue: 'J96.01',
          reason: 'Clinical documentation supports acute respiratory failure as primary indication for chest X-ray',
          riskLevel: 'medium',
        },
      ],
      requiredDocuments: [
        { documentType: 'Clinical notes', reason: 'To support the revised diagnosis' },
        { documentType: 'Physician attestation', reason: 'To confirm clinical findings support diagnosis change' },
      ],
      resubmissionInstructions: {
        claimFrequencyCode: '7',
        submissionType: 'Electronic',
        notes: 'Resubmit with corrected diagnosis. If payer denies again, submit formal appeal with clinical records.',
      },
      confidenceScore: 0.75,
      riskLevel: 'medium',
      complianceNotes: ['Diagnosis change must be supported by clinical documentation documented at time of service.'],
      createdAt: '2024-10-17T14:00:00Z',
    },
    qualityCheck: {
      overallResult: 'warning',
      validationFindings: [
        { check: 'Correction addresses denial reason', result: 'pass', details: 'Diagnosis change addresses medical necessity denial' },
        { check: 'Required fields complete', result: 'pass', details: 'All required fields populated' },
        { check: 'Coding changes supported', result: 'warning', details: 'Diagnosis change requires strong clinical documentation support' },
        { check: 'Compliance risk assessment', result: 'pass', details: 'No compliance risk if clinical documentation supports change' },
      ],
      blockingIssues: [],
      warnings: [
        { warning: 'Diagnosis change from R91.8 to J96.01 is significant', recommendedAction: 'Ensure thorough clinical documentation review before resubmission' },
      ],
      recommendation: 'approve_for_review',
      confidenceScore: 0.78,
      checkedAt: '2024-10-18T09:00:00Z',
    },
    createdAt: '2024-10-15T11:20:00Z',
    updatedAt: '2024-10-18T09:00:00Z',
  },
  {
    id: 'DEN-005',
    claimNumber: 'CLM-2024-00455',
    patientName: 'Patricia Davis',
    patientDOB: '1948-12-03',
    payerName: 'Blue Cross Blue Shield',
    payerId: 'BCBS-67890',
    providerNPI: '4567890123',
    dateOfService: '2024-08-20',
    denialDate: '2024-09-05',
    cptCode: '99215',
    modifier: '',
    diagnosisCode: 'I10',
    billedAmount: 450.00,
    deniedAmount: 450.00,
    carcCode: 'CO-29',
    rarcCode: 'N461',
    adjustmentGroupCode: 'CO',
    denialCategory: 'timely_filing',
    status: 'Closed',
    priority: 'low',
    analysis: {
      denialSummary: 'Claim denied for timely filing. The claim was not submitted within the payer filing deadline.',
      rootCauseCategory: 'Administrative Delay',
      rootCauseDetail: 'Claim submission delayed 52 days past the 90-day filing deadline due to billing backlog.',
      denialCategory: 'timely_filing',
      preventable: true,
      correctable: false,
      appealRecommended: false,
      confidenceScore: 0.97,
      recommendedNextAction: 'Write off as non-recoverable. Implement process improvements to prevent future timely filing denials.',
      requiredInformation: [],
      complianceNotes: ['Timely filing denials are generally not appealable unless payer error can be documented.'],
      analyzedAt: '2024-09-06T10:00:00Z',
    },
    createdAt: '2024-09-05T15:30:00Z',
    updatedAt: '2024-09-06T10:00:00Z',
  },
  {
    id: 'DEN-006',
    claimNumber: 'CLM-2024-00456',
    patientName: 'David Martinez',
    patientDOB: '1990-02-14',
    payerName: 'UnitedHealthcare',
    payerId: 'UHC-87726',
    providerNPI: '1234567890',
    dateOfService: '2024-11-20',
    denialDate: '2024-12-05',
    cptCode: '29881',
    modifier: 'RT',
    diagnosisCode: 'M23.21',
    billedAmount: 5800.00,
    deniedAmount: 5800.00,
    carcCode: 'CO-50',
    rarcCode: 'N430',
    adjustmentGroupCode: 'CO',
    denialCategory: 'authorization',
    status: 'New',
    priority: 'critical',
    createdAt: '2024-12-05T08:45:00Z',
    updatedAt: '2024-12-05T08:45:00Z',
  },
  {
    id: 'DEN-007',
    claimNumber: 'CLM-2024-00457',
    patientName: 'Linda Johnson',
    patientDOB: '1955-09-28',
    payerName: 'Humana',
    payerId: 'HUM-11111',
    providerNPI: '5678901234',
    dateOfService: '2024-11-22',
    denialDate: '2024-12-06',
    cptCode: '93000',
    modifier: '',
    diagnosisCode: 'I25.10',
    billedAmount: 275.00,
    deniedAmount: 275.00,
    carcCode: 'CO-197',
    rarcCode: 'N574',
    adjustmentGroupCode: 'CO',
    denialCategory: 'authorization',
    status: 'New',
    priority: 'high',
    createdAt: '2024-12-06T13:10:00Z',
    updatedAt: '2024-12-06T13:10:00Z',
  },
  {
    id: 'DEN-008',
    claimNumber: 'CLM-2024-00458',
    patientName: 'Michael Brown',
    patientDOB: '1978-06-05',
    payerName: 'Aetna',
    payerId: 'AET-54321',
    providerNPI: '2345678901',
    dateOfService: '2024-11-25',
    denialDate: '2024-12-08',
    cptCode: '99213',
    modifier: '',
    diagnosisCode: 'J06.9',
    billedAmount: 185.00,
    deniedAmount: 185.00,
    carcCode: 'PR-1',
    rarcCode: 'N490',
    adjustmentGroupCode: 'PR',
    denialCategory: 'eligibility',
    status: 'Analyzed',
    priority: 'normal',
    analysis: {
      denialSummary: 'Claim denied as patient responsibility - deductible amount. This is a PR (Patient Responsibility) adjustment.',
      rootCauseCategory: 'Patient Financial Responsibility',
      rootCauseDetail: 'Patient has not met annual deductible. This is a valid patient responsibility, not a payer error.',
      denialCategory: 'eligibility',
      preventable: false,
      correctable: false,
      appealRecommended: false,
      confidenceScore: 0.99,
      recommendedNextAction: 'Bill patient for deductible amount. Update patient account records. No appeal needed.',
      requiredInformation: [
        { item: 'Patient deductible status', reasonNeeded: 'To confirm remaining deductible amount' },
      ],
      complianceNotes: ['PR-1 is patient responsibility. Balance should be transferred to patient.'],
      analyzedAt: '2024-12-09T08:00:00Z',
    },
    createdAt: '2024-12-08T16:45:00Z',
    updatedAt: '2024-12-09T08:00:00Z',
  },
  {
    id: 'DEN-009',
    claimNumber: 'CLM-2024-00459',
    patientName: 'Jennifer Lee',
    patientDOB: '1982-04-19',
    payerName: 'Cigna',
    payerId: 'CIG-98765',
    providerNPI: '3456789012',
    dateOfService: '2024-11-28',
    denialDate: '2024-12-10',
    cptCode: '90834',
    modifier: '',
    diagnosisCode: 'F41.1',
    billedAmount: 220.00,
    deniedAmount: 220.00,
    carcCode: 'CO-4',
    rarcCode: 'N322',
    adjustmentGroupCode: 'CO',
    denialCategory: 'coding_error',
    status: 'New',
    priority: 'high',
    createdAt: '2024-12-10T09:30:00Z',
    updatedAt: '2024-12-10T09:30:00Z',
  },
  {
    id: 'DEN-010',
    claimNumber: 'CLM-2024-00460',
    patientName: 'William Anderson',
    patientDOB: '1969-08-11',
    payerName: 'Medicare',
    payerId: 'MCR-00126',
    providerNPI: '4567890123',
    dateOfService: '2024-11-10',
    denialDate: '2024-11-28',
    cptCode: '99214',
    modifier: '25',
    diagnosisCode: 'E11.9',
    billedAmount: 340.00,
    deniedAmount: 340.00,
    carcCode: 'CO-11',
    rarcCode: 'N437',
    adjustmentGroupCode: 'CO',
    denialCategory: 'coding_error',
    status: 'Resubmitted',
    priority: 'high',
    analysis: {
      denialSummary: 'Claim denied because the diagnosis does not support the level of service billed.',
      rootCauseCategory: 'Coding Error',
      rootCauseDetail: 'E/M level 99214 not supported by documented medical decision-making complexity.',
      denialCategory: 'coding_error',
      preventable: true,
      correctable: true,
      appealRecommended: true,
      confidenceScore: 0.85,
      recommendedNextAction: 'Review documentation to determine correct E/M level. Resubmit with appropriate code.',
      requiredInformation: [
        { item: 'Complete clinical documentation', reasonNeeded: 'To determine correct E/M level' },
        { item: 'MDM worksheet', reasonNeeded: 'To document level of medical decision making' },
      ],
      complianceNotes: ['Downcoding may be appropriate if documentation does not support 99214.'],
      analyzedAt: '2024-11-29T10:00:00Z',
    },
    correction: {
      correctionType: 'Code Correction',
      correctionSummary: 'Downcode E/M from 99214 to 99213 based on documentation review.',
      correctionRationale: 'Clinical documentation supports straightforward medical decision-making, consistent with 99213 rather than 99214.',
      proposedChanges: [
        {
          fieldPath: 'CPTCode',
          originalValue: '99214',
          proposedValue: '99213',
          reason: 'Documentation supports straightforward MDM, not moderate complexity',
          riskLevel: 'low',
        },
      ],
      requiredDocuments: [
        { documentType: 'Clinical documentation', reason: 'To support the corrected E/M level' },
      ],
      resubmissionInstructions: {
        claimFrequencyCode: '7',
        submissionType: 'Electronic',
        notes: 'Resubmit with corrected CPT code 99213. No additional documentation needed.',
      },
      confidenceScore: 0.92,
      riskLevel: 'low',
      complianceNotes: ['Downcoding is appropriate when documentation does not support higher level.'],
      createdAt: '2024-11-30T11:00:00Z',
    },
    qualityCheck: {
      overallResult: 'pass',
      validationFindings: [
        { check: 'Correction addresses denial reason', result: 'pass', details: 'Code correction addresses the diagnosis/code mismatch' },
        { check: 'Required fields complete', result: 'pass', details: 'All required fields populated' },
        { check: 'Coding changes supported', result: 'pass', details: 'Documentation supports downcoded E/M level' },
        { check: 'Compliance risk assessment', result: 'pass', details: 'Downcoding is compliant and reduces audit risk' },
      ],
      blockingIssues: [],
      warnings: [],
      recommendation: 'approve_for_review',
      confidenceScore: 0.93,
      checkedAt: '2024-12-01T08:30:00Z',
    },
    createdAt: '2024-11-28T12:15:00Z',
    updatedAt: '2024-12-01T08:30:00Z',
  },
  {
    id: 'DEN-011',
    claimNumber: 'CLM-2024-00461',
    patientName: 'Elizabeth Taylor',
    patientDOB: '1975-01-25',
    payerName: 'Blue Cross Blue Shield',
    payerId: 'BCBS-67890',
    providerNPI: '5678901234',
    dateOfService: '2024-11-30',
    denialDate: '2024-12-12',
    cptCode: '70553',
    modifier: '',
    diagnosisCode: 'G43.909',
    billedAmount: 4500.00,
    deniedAmount: 4500.00,
    carcCode: 'CO-15',
    rarcCode: 'N381',
    adjustmentGroupCode: 'CO',
    denialCategory: 'missing_information',
    status: 'New',
    priority: 'high',
    createdAt: '2024-12-12T14:20:00Z',
    updatedAt: '2024-12-12T14:20:00Z',
  },
  {
    id: 'DEN-012',
    claimNumber: 'CLM-2024-00462',
    patientName: 'Richard Garcia',
    patientDOB: '1960-10-07',
    payerName: 'UnitedHealthcare',
    payerId: 'UHC-87726',
    providerNPI: '6789012345',
    dateOfService: '2024-10-15',
    denialDate: '2024-11-01',
    cptCode: '27130',
    modifier: '',
    diagnosisCode: 'M16.11',
    billedAmount: 32000.00,
    deniedAmount: 32000.00,
    carcCode: 'CO-197',
    rarcCode: 'N574',
    adjustmentGroupCode: 'CO',
    denialCategory: 'authorization',
    status: 'Analyzed',
    priority: 'critical',
    analysis: {
      denialSummary: 'Claim denied because precertification/authorization was not obtained for this service.',
      rootCauseCategory: 'Authorization Process Failure',
      rootCauseDetail: 'Surgical precertification was not obtained prior to total hip arthroplasty. Authorization is required for this procedure.',
      denialCategory: 'authorization',
      preventable: true,
      correctable: true,
      appealRecommended: true,
      confidenceScore: 0.80,
      recommendedNextAction: 'Obtain retrospective authorization if payer allows. Appeal with clinical urgency documentation.',
      requiredInformation: [
        { item: 'Clinical urgency documentation', reasonNeeded: 'To support retrospective authorization request' },
        { item: 'Surgical records and notes', reasonNeeded: 'To demonstrate medical necessity' },
      ],
      complianceNotes: ['Some payers allow retrospective authorization within specific timeframes. Check payer policy.'],
      analyzedAt: '2024-11-02T09:00:00Z',
    },
    createdAt: '2024-11-01T16:00:00Z',
    updatedAt: '2024-11-02T09:00:00Z',
  },
  {
    id: 'DEN-013',
    claimNumber: 'CLM-2024-00463',
    patientName: 'Susan White',
    patientDOB: '1988-03-22',
    payerName: 'Humana',
    payerId: 'HUM-11111',
    providerNPI: '7890123456',
    dateOfService: '2024-12-01',
    denialDate: '2024-12-15',
    cptCode: '97110',
    modifier: 'GP',
    diagnosisCode: 'M17.11',
    billedAmount: 180.00,
    deniedAmount: 180.00,
    carcCode: 'OA-23',
    rarcCode: 'N325',
    adjustmentGroupCode: 'OA',
    denialCategory: 'coding_error',
    status: 'New',
    priority: 'normal',
    createdAt: '2024-12-15T10:00:00Z',
    updatedAt: '2024-12-15T10:00:00Z',
  },
  {
    id: 'DEN-014',
    claimNumber: 'CLM-2024-00464',
    patientName: 'Thomas Harris',
    patientDOB: '1952-07-14',
    payerName: 'Medicare',
    payerId: 'MCR-00126',
    providerNPI: '8901234567',
    dateOfService: '2024-09-20',
    denialDate: '2024-10-10',
    cptCode: '80053',
    modifier: '',
    diagnosisCode: 'Z00.00',
    billedAmount: 165.00,
    deniedAmount: 165.00,
    carcCode: 'CO-109',
    rarcCode: 'N518',
    adjustmentGroupCode: 'CO',
    denialCategory: 'eligibility',
    status: 'Closed',
    priority: 'low',
    analysis: {
      denialSummary: 'Claim denied because the patient is not covered under this plan/program.',
      rootCauseCategory: 'Eligibility Verification Failure',
      rootCauseDetail: 'Patient Medicare coverage lapsed due to non-payment of Part B premium. Coverage was inactive on date of service.',
      denialCategory: 'eligibility',
      preventable: true,
      correctable: false,
      appealRecommended: false,
      confidenceScore: 0.96,
      recommendedNextAction: 'Verify if patient has reinstated coverage. If not, bill patient directly. Implement real-time eligibility checks.',
      requiredInformation: [
        { item: 'Current Medicare coverage status', reasonNeeded: 'To determine if coverage has been reinstated retroactively' },
      ],
      complianceNotes: ['Check MSP (Medicare Secondary Payer) rules before billing patient.'],
      analyzedAt: '2024-10-11T08:30:00Z',
    },
    createdAt: '2024-10-10T11:45:00Z',
    updatedAt: '2024-10-11T08:30:00Z',
  },
  {
    id: 'DEN-015',
    claimNumber: 'CLM-2024-00465',
    patientName: 'Karen Robinson',
    patientDOB: '1995-12-08',
    payerName: 'Aetna',
    payerId: 'AET-54321',
    providerNPI: '9012345678',
    dateOfService: '2024-12-02',
    denialDate: '2024-12-18',
    cptCode: '99211',
    modifier: '',
    diagnosisCode: 'Z23',
    billedAmount: 95.00,
    deniedAmount: 95.00,
    carcCode: 'CO-16',
    rarcCode: 'N378',
    adjustmentGroupCode: 'CO',
    denialCategory: 'missing_information',
    status: 'New',
    priority: 'normal',
    createdAt: '2024-12-18T15:30:00Z',
    updatedAt: '2024-12-18T15:30:00Z',
  },
  {
    id: 'DEN-016',
    claimNumber: 'CLM-2024-00466',
    patientName: 'Daniel Clark',
    patientDOB: '1970-05-17',
    payerName: 'Cigna',
    payerId: 'CIG-98765',
    providerNPI: '0123456789',
    dateOfService: '2024-11-05',
    denialDate: '2024-11-20',
    cptCode: '64483',
    modifier: '50',
    diagnosisCode: 'M54.5',
    billedAmount: 1200.00,
    deniedAmount: 1200.00,
    carcCode: 'CO-4',
    rarcCode: 'N322',
    adjustmentGroupCode: 'CO',
    denialCategory: 'coding_error',
    status: 'Corrected',
    priority: 'high',
    analysis: {
      denialSummary: 'Claim denied due to procedure code inconsistency with modifier or missing modifier.',
      rootCauseCategory: 'Coding Error',
      rootCauseDetail: 'Bilateral procedure modifier 50 applied incorrectly - some payers require two line items instead of modifier 50.',
      denialCategory: 'coding_error',
      preventable: true,
      correctable: true,
      appealRecommended: false,
      confidenceScore: 0.88,
      recommendedNextAction: 'Resubmit as two separate line items (LT and RT modifiers) per payer billing guidelines.',
      requiredInformation: [
        { item: 'Payer bilateral billing policy', reasonNeeded: 'To confirm correct billing format' },
      ],
      complianceNotes: ['Check payer-specific bilateral billing rules before resubmission.'],
      analyzedAt: '2024-11-21T09:15:00Z',
    },
    correction: {
      correctionType: 'Modifier Correction',
      correctionSummary: 'Remove modifier 50 and split into two line items with LT and RT modifiers.',
      correctionRationale: 'Cigna requires bilateral procedures to be billed as two separate line items with LT/RT modifiers, not modifier 50.',
      proposedChanges: [
        {
          fieldPath: 'LineItem[1].Modifier',
          originalValue: '50',
          proposedValue: 'LT',
          reason: 'Payer requires separate line items for bilateral procedures',
          riskLevel: 'low',
        },
        {
          fieldPath: 'LineItem[2].Modifier',
          originalValue: '',
          proposedValue: 'RT',
          reason: 'Add second line item for right side with RT modifier',
          riskLevel: 'low',
        },
      ],
      requiredDocuments: [],
      resubmissionInstructions: {
        claimFrequencyCode: '7',
        submissionType: 'Electronic',
        notes: 'Resubmit with two line items: 64483-LT and 64483-RT. Each at half the bilateral fee.',
      },
      confidenceScore: 0.90,
      riskLevel: 'low',
      complianceNotes: ['Follow payer-specific bilateral billing guidelines.'],
      createdAt: '2024-11-22T10:30:00Z',
    },
    createdAt: '2024-11-20T13:00:00Z',
    updatedAt: '2024-11-22T10:30:00Z',
  },
  {
    id: 'DEN-017',
    claimNumber: 'CLM-2024-00467',
    patientName: 'Nancy Lewis',
    patientDOB: '1943-08-30',
    payerName: 'Blue Cross Blue Shield',
    payerId: 'BCBS-67890',
    providerNPI: '1234567890',
    dateOfService: '2024-10-08',
    denialDate: '2024-10-25',
    cptCode: '74177',
    modifier: '',
    diagnosisCode: 'R10.9',
    billedAmount: 3200.00,
    deniedAmount: 3200.00,
    carcCode: 'CO-50',
    rarcCode: 'N430',
    adjustmentGroupCode: 'CO',
    denialCategory: 'authorization',
    status: 'New',
    priority: 'critical',
    createdAt: '2024-10-25T08:20:00Z',
    updatedAt: '2024-10-25T08:20:00Z',
  },
  {
    id: 'DEN-018',
    claimNumber: 'CLM-2024-00468',
    patientName: 'Christopher Walker',
    patientDOB: '1980-11-12',
    payerName: 'UnitedHealthcare',
    payerId: 'UHC-87726',
    providerNPI: '2345678901',
    dateOfService: '2024-12-05',
    denialDate: '2024-12-20',
    cptCode: '43239',
    modifier: '',
    diagnosisCode: 'K21.0',
    billedAmount: 4800.00,
    deniedAmount: 4800.00,
    carcCode: 'CO-16',
    rarcCode: 'N286',
    adjustmentGroupCode: 'CO',
    denialCategory: 'missing_information',
    status: 'New',
    priority: 'high',
    createdAt: '2024-12-20T11:00:00Z',
    updatedAt: '2024-12-20T11:00:00Z',
  },
];

export default sampleDenials;
